<?php
/***************************************
 *** Customer Photo Crop Extension ***
 ***************************************
 *
 * @copyright   Copyright (c) 2015
 * @company     NetAttingo Technologies
 * @package     Netgo_Customerpic
 * @author 		Vipin
 * @dev			77vips@gmail.com
 *
 */
$_helper = Mage::helper('netgo_customerpic');
$thumb_width = $_helper->getThumbWidth();
$thumb_height = $_helper->getThumbHeight();
$base_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
?>
<div id="popup_upload">
	<div class="form_upload">
		<span class="close" onclick="close_popup('popup_upload')">x</span>
		<h2>Upload photo</h2>
		<form action="<?php echo $base_url; ?>netgo/customerpic/upload" method="post" enctype="multipart/form-data" target="upload_frame" onsubmit="submit_photo('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>')">
			<input type="file" name="photo" id="photo" class="file_input">
            <div id="loading_progress"></div>
			<input type="submit" value="Upload photo" id="upload_btn">
		</form>
		<iframe name="upload_frame" class="upload_frame"></iframe>
	</div>
</div> 
<div id="popup_crop">
	<div class="form_crop">
		<span class="close" onclick="close_popup('popup_crop')">x</span>
		<h2>Crop photo</h2> 
		<img id="cropbox" /> 
		<form>
			<input type="hidden" id="x" name="x" />
			<input type="hidden" id="y" name="y" />
			<input type="hidden" id="w" name="w" />
			<input type="hidden" id="h" name="h" />
			<input type="hidden" id="photo_url" name="photo_url" />
			<input type="button" value="Crop Image" id="crop_btn" onclick="crop_photo('<?php echo $thumb_width; ?>', '<?php echo $thumb_height; ?>', '<?php echo $base_url; ?>')" />
		</form>
	</div>
</div>
<div class="upl-right"> 
	<div class="upl-image">
		<div class="profilepicbutton x1">
			<div class="content"> 
				<div id="photo_container" class="brw-content">
					<span class="upload_btn-img"><img alt=""  src="<?php echo $this->getCustomerPhoto(); ?>" />
					<span class="upload_btn_img" onclick="show_popup('popup_upload')"><span class="ed-txt">Upload</span></span>			
					</span>  
				</div>
			</div>
		</div> 
	</div> 
</div>

