<?php
/******************************************************
 * @package Pav Megamenu module for Opencart 1.5.x
 * @version 1.0
 * @author http://www.pavothemes.com
 * @copyright	Copyright (C) Feb 2013 PavoThemes.com <@emai:pavothemes@gmail.com>.All rights reserved.
 * @license		GNU General Public License version 2
*******************************************************/
	
	$live_site_url = $this->getLiveSiteUrl();
	$widgets = $this->getWidgets();
	$action_submenu = $this->getGenSubmenuLink();
 	$ajxgenmenu = $this->getAjaxGenmenuLink();
 	$ajxmenuinfo = $this->getAjaxMenuinfoLink();
 	$action_widget = $this->getRenderWidgetLink();
 	$action_addwidget = $this->getCreateWidgetLink();
 	$liveedit_action = $this->getLiveEditLink();
 	$action_backlink = $this->getBackLink();
	$module_row=0;
?>
<?php echo $this->getFormInitScripts() ?>
<title>Mega Menu Title</title>
<style type="text/css">
	#page-content{
		min-height: 1200px;
		width: 100%;
		padding-bottom: 100px
	}
	.adminhtml-adminhtml-megamenu-liveedit .header, .adminhtml-adminhtml-megamenu-liveedit .notification-global, .adminhtml-adminhtml-megamenu-liveedit .footer{
		display: none;
	}
</style>
<div id="page-content">
<div id="menu-form"  style="display: none; left: 340px; top: 15px; max-width:600px" class="popover top out form-setting">
		<div class="arrow"></div>
		<h3 style="display: block;" class="popover-title">Sub Menu Setting <span class="badge pull-right"><?php echo Mage::helper("ves_megamenu")->__('Close');?></span></h3>
		<div class="popover-content"> 
			<form  method="post" action="<?php echo $liveedit_action;?>"  enctype="multipart/form-data" >
			<div class="col-lg-12">	
			<table class="table table-hover">
		 
				<tr>
					<td><?php echo Mage::helper("ves_megamenu")->__('Create submenu');?></td>
					<td>
						<select name="menu_submenu" class="menu_submenu">
							<option value="0"><?php echo Mage::helper("ves_megamenu")->__('No');?></option>
							<option value="1"><?php echo Mage::helper("ves_megamenu")->__('Yes');?></option>
						</select>
					</td>
				</tr>
				
				<tr>
					<td><?php echo Mage::helper("ves_megamenu")->__('Width of submenu');?></td>
					<td>
						 <input type="text" name="menu_subwidth" class="menu_subwidth"> 
					</td>
				</tr>
				<tr>
					<td><?php echo Mage::helper("ves_megamenu")->__('Alignment' ); ?></td>
					<td>
						<div class="btn-group button-alignments">
						  <button type="button" class="btn btn-default" data-option="aligned-left"><span class="fa fa-align-left"></span></button>
						  <button type="button" class="btn btn-default" data-option="aligned-center"><span class="fa fa-align-center"></span></button>
						  <button type="button" class="btn btn-default" data-option="aligned-right"><span class="fa fa-align-right"></span></button>
						  <button type="button" class="btn btn-default" data-option="aligned-fullwidth"><span class="fa fa-align-justify"></span></button>
						</div>

					</td>
				</tr>
					<tr>
					<td colspan="2">
						<button type="button" class="add-row btn btn-success btn-sm"><?php echo Mage::helper("ves_megamenu")->__('add row');?></button>
						<button type="button" class="remove-row btn btn-default  btn-sm"><?php echo Mage::helper("ves_megamenu")->__('remove row');?></button>
						| <button type="button" class="add-col btn btn-success  btn-sm"><?php echo Mage::helper("ves_megamenu")->__('add clumn');?></button>
					</td>
				</tr>
			</table>
			<input type="hidden" name="menu_id">
			</div>
		 
			</form>
		</div>
	</div>


	<div id="column-form" style="display: none; left: 340px; top: 45px;" class="popover top   form-setting">
		<div class="arrow"></div>
		<h3 style="display: block;" class="popover-title">Column Setting <span class="badge pull-right"><?php echo Mage::helper("ves_megamenu")->__('Close');?></span></h3>
		<div class="popover-content"> 
			<form    method="post" action="<?php echo $liveedit_action;?>"  enctype="multipart/form-data" >
			<table class="table table-hover">
				<tr>
					<td><?php echo Mage::helper("ves_megamenu")->__('addition class');?></td>
					<td>
						<input type="text" name="colclass"> 
					</td>
				</tr>
				<tr>
					<td><?php echo Mage::helper("ves_megamenu")->__('Column Width');?></td>
					<td>
						<select class="colwidth" name="colwidth">
							<?php for( $i = 1; $i<=12; $i++ )  { ?>
							<option value="<?php echo $i;?>"><?php echo $i;?></option>
							<?php } ?>
						</select>
					</td>
				</tr>
				<tr>
					<td colspan="2">	<button type="button" class="remove-col btn btn-default  btn-sm"><?php echo Mage::helper("ves_megamenu")->__('remove column');?></button> </td>
				</tr>	
			</table>
			</form>
		</div>
	</div>


	<div  id="submenu-form" style="display: none; left: 340px; top: 45px;" class="popover top  form-setting">
		<div class="arrow"></div>
		<h3 style="display: block;" class="popover-title"><?php echo Mage::helper("ves_megamenu")->__('setting submenu');?><span class="badge pull-right"><?php echo Mage::helper("ves_megamenu")->__('Close');?></span></h3>
		<div class="popover-content"> 
			<form   method="post" action="<?php echo $liveedit_action;?>"  enctype="multipart/form-data" >
									   					
				<input type="hidden" name="submenu_id">
				<table class="table table-hover">
					<tr>
						<td><?php echo Mage::helper("ves_megamenu")->__('group submenu');?></td>
						<td>
							<select name="submenu_group">
								<option value="0"><?php echo Mage::helper("ves_megamenu")->__('No');?></option>
								<option value="1"><?php echo Mage::helper("ves_megamenu")->__('Yes');?></option>
							</select>
						</td>
					</tr>

				</table>
			</form>
		</div>
	</div>


	<div  id="widget-form" style="display: none; left: 340px;  min-width:400px" class="popover bottom   form-setting">
		<div class="arrow"></div>
		<h3 style="display: block;" class="popover-title"><?php echo Mage::helper("ves_megamenu")->__('widget setting');?><span class="badge pull-right"><?php echo Mage::helper("ves_megamenu")->__('Close');?></span></h3>
		<div class="popover-content"> 
			<?php if( !empty($widgets) ) { ?>
			 <select name="inject_widget"> 
			 	<option value=""></option>
			 <?php foreach( $widgets as $w ) { ?>
				<option value="<?php echo $w->getId(); ?>"><?php echo $w->getName(); ?></option>
			 <?php } ?>
			</select>
			<button type="button" id="btn-inject-widget" class="btn btn-primary btn-sm"><?php echo Mage::helper("ves_megamenu")->__('Insert');?></button>
			<span><?php echo $this->__(" - OR - "); ?></span>
			<button type="button" id="btn-inject-submenu" class="btn btn-warning btn-sm"><?php echo Mage::helper("ves_megamenu")->__('Insert Sub Menus');?></button>
			<?php } ?>
		</div>
	 	
	</div>
		

<div id="content-s">

	<div class="container">
		<div class="page-header">
		<h1 >Live Mega Menu Editor <small> - Easy to make the menu to be great and powerly</small></h1>
 		</div>


	 	<div class="bs-example">
	      <div class="alert alert-danger fade in">
	        <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
	        <strong>By using this tool, allow to create sub menu having multiple rows and  multiple columns. You can inject widgets inside columns or group sub menus in same level of parent.Note: Some configurations as group, columns width setting will be overrided</strong>  
	      </div>
	    </div>


 	</div>
   	<div id="pav-megamenu-liveedit">

		<div id="toolbar" class="container">
			<div id="menu-toolbars">
					   						
				<div>
					<div class="pull-right">
						
						<a href="<?php echo $action_addwidget; ?>" id="btn-add-widget" rel="refresh-page" class="btn btn-modal btn-success btn-action">Add Widget</a> - <a   href="<?php echo Mage::getBaseUrl();?>" class="btn btn-modal btn-primary btn-sm btn-action" ><?php echo Mage::helper("ves_megamenu")->__('Preview on live site');?></a> | 
						<a id="unset-data-menu" href="#" class="btn btn-danger btn-action"><?php echo Mage::helper("ves_megamenu")->__('Reset megamenu');?></a>
						<button id="save-data-menu" class="btn btn-warning">Save</button>
					</div>
					<a id="save-data-back" class="btn btn-default" href="<?php echo $action_backlink;?>"><?php echo Mage::helper("ves_megamenu")->__('Back');?></a>
				</div>

				</div>
			</div>
		   		

			<div class="container"><div class="megamenu-wrap">
				<div class="progress" id="pavo-progress">
				  <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 00%;">
				    <span class="sr-only">60% Complete</span>
				  </div>
			</div>
	   		<div id="megamenu-content">
	   		</div></div>
		 	</div>
   	</div>
</div>
 </div>


  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title"><?php echo Mage::helper("ves_megamenu")->__('Preview on live site');?></h4>
        </div>
        <div class="modal-body">
         	
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo Mage::helper("ves_megamenu")->__('Close'); ?></button>
        </div>
      </div> 
    </div> 
  </div> 


<script type="text/javascript">
	jQuery(".btn-modal").click( function(){
		jQuery('#myModal .modal-dialog').css('width',980);
		var a = jQuery( '<span class="glyphicon glyphicon-refresh"></span><iframe src="'+jQuery(this).attr('href')+'" style="width:98%;height:600px; display:none"/>'  );
		jQuery('#myModal .modal-body').html( a );
			
		jQuery('#myModal').modal( );
		jQuery('#myModal').attr('rel', jQuery(this).attr('rel') );
		jQuery( a  ).load( function(){  
			
			jQuery('#myModal .modal-body .glyphicon-refresh').hide();
	 		jQuery('#myModal .modal-body iframe').show();
		} );
		return false;
	} );
	
	jQuery('#myModal').on('hidden.bs.modal', function () { 
	 	 if( jQuery(this).attr('rel') == 'refresh-page' ){
	 	 	location.reload();
	 	 }
	})


	var _action 	   = '<?php echo str_replace("&amp;","&",$ajxgenmenu);?>';
	var _action_submenu 	   = '<?php echo str_replace("&amp;","&",$action_submenu);?>';
	var _action_menu   = '<?php echo str_replace("&amp;","&",$ajxmenuinfo);?>';
	var _action_widget = '<?php echo str_replace("&amp;","&",$action_widget);?>';
	jQuery("#megamenu-content").PavMegamenuEditor( {'action':_action, 'action_menu':_action_menu,'action_widget':_action_widget} );

</script>
 
