<?php
//Load Theme Settings
$class = '';
$enable_ajax_cart = false;
if(Mage::helper("productlist")->checkModuleInstalled("Ves_Themesettings"))
{
    $ves = $this->helper('themesettings');
    $ajax = $this->helper('ajax');
    $helpImg = $this->helper('themesettings/image');
    
    $alt_image_column = $ves->getConfig('category_product/alt_image_column');
    $alt_image_column_value = $ves->getConfig('category_product/alt_image_column_value');

    // Product Settings
    $display_name_single_line = $ves->getConfig('category_product/display_name_single_line');
    if($display_name_single_line){
        $class .= ' single-line-name';
    }
    // Product Grid
    $equal_height = $ves->getConfig('category_grid/equal_height');
    if($equal_height){
        $class .= ' equal-height';
    }
    $hover_effect = $ves->getConfig('category_grid/hover_effect');
    if($equal_height){
        $class .= ' hover-effect';
    }
    $disable_hover_effect = $ves->getConfig('category_grid/disable_hover_effect');

    // Ajax Cart, Quick View
    $ajaxcart = $ajax->getConfig('general_setting/enable_ajaxcart');
    $enable_ajax_cart = $ajaxcart;
    $show_addtocart = $ajax->getConfig('general_setting/show_addtocart');
    $show_quickview = $ajax->getConfig('general_setting/show_quickview');
    $popup_quickview_width = $ajax->getConfig('general_setting/popup_quickview_width');
    $popup_quickview_height = $ajax->getConfig('general_setting/popup_quickview_height');

    // Product Label
    $enable_new_icon = $ves->getConfig('product_labels/new');
    $enable_sale_icon = $ves->getConfig('product_labels/sale');

    // Product Settings
    $_helper = $this->helper('catalog/output');
    $show_name = $ves->getConfig('product_slider/show_name');

    $show_short_description = $ves->getConfig('product_slider/show_short_description');
    $short_max_char = $ves->getConfig('product_slider/short_max_char');
    $show_price = $ves->getConfig('product_slider/show_price');
    $show_rating = $ves->getConfig('product_slider/show_rating');
    $show_learnmore = $ves->getConfig('product_slider/show_learnmore');
    $show_countdowntimer = $ves->getConfig('product_slider/show_countdowntimer');

    $show_addtolinks = $ves->getConfig('product_slider/show_addtolinks');

    $alt_image = $ves->getConfig('product_slider/alt_image');
    $alt_image_column = $ves->getConfig('product_slider/alt_image_column');
    $alt_image_column_value = $ves->getConfig('product_slider/alt_image_column_value');

    $aspect_ratio = $ves->getConfig('product_slider/aspect_ratio');
    $imgWidth = (int)$ves->getConfig('product_slider/image_width');
    $imgHeight = $imgWidth;
    //If image width is not specified, use default values
    if ($imgWidth <= 0)
    {
        $imgWidth = 295;
        $imgHeight = 295;
    }

    if($aspect_ratio){
        $imgHeight = 0;
        $catViewKeepFrame = FALSE;
    }else{
        $catViewKeepFrame = TRUE;
    }

    if (Mage::registry('catViewKeepFrame') === NULL){
        Mage::register('catViewKeepFrame', $catViewKeepFrame);
    }

    // Quickview Design
    $quickview_format = $ves->getCfgDesign('icons/quickview_format');
    $quickview_text = $ves->getCfgDesign('icons/quickview_text');
    $quickview_class = $ves->getCfgDesign('icons/quickview_class');

    // Addtocart Design
    $addtocart_format = $ves->getCfgDesign('icons/addtocart_format');
    $addtocart_text = $ves->getCfgDesign('icons/addtocart_text');
    $addtocart_class = $ves->getCfgDesign('icons/addtocart_class');

    // Compare Design
    $compare_format = $ves->getCfgDesign('icons/compare_format');
    $compare_text = $ves->getCfgDesign('icons/compare_text');
    $compare_class = $ves->getCfgDesign('icons/compare_class');

    // Wishlist Design
    $wishlist_format = $ves->getCfgDesign('icons/wishlist_format');
    $wishlist_text = $ves->getCfgDesign('icons/wishlist_text');
    $wishlist_class = $ves->getCfgDesign('icons/wishlist_class');

}

if($show_countdowntimer){
    $widget_show_countdowntimer = $this->getData('show_countdowntimer');
    if($widget_show_countdowntimer == "false"){
        $show_countdowntimer = false;
    }
}
//End Load Theme Settings
// Override Theme Settings
$show_quickview = $this->getConfig('show_quickview');
$popup_quickview_width = $this->getConfig('popup_quickview_width');
$popup_quickview_height = $this->getConfig('popup_quickview_height');

$display_name_single_line = $this->getConfig('display_name_single_line');
if($display_name_single_line){
    $class .= ' single-line-name';
}

// End Override Theme Settings
//Init carousel data information
$this->_initCarouselData();
$processor = Mage::helper('cms')->getPageTemplateProcessor();

$moduleId = "ves_productlist_carousel_".rand().time();
$title = $this->getConfig("title", "");
$show_rule_title = $this->getConfig("show_rule_title");
$freemode = $this->getConfig("freemode");
$loop = $this->getConfig("loop");
$stylecls = $this->getConfig("stylecls");
$slider_height = (int)$this->getConfig("slider_height",0);
$slider_width = (int)$this->getConfig("slider_width",0);
if($slider_height) {
    $slider_height = "height: ".$slider_height."px;";
} else {
    $slider_height = "";
}
if($slider_width) {
    $slider_width = "width: ".$slider_width."px;";
} else {
    $slider_width = "";
}
$price_prefix = "_productlist_carousel_".rand(1,9)+rand().time();
//Product Information Settings

$enable_rule_info = (int)$this->getConfig("enable_rule_info", 0);
if($enable_rule_info) {
    $rule_info = $this->getRuleModel();
}
$enable_rule_short_description = (int)$this->getConfig("enable_rule_short_description", 1);
$show_all_button = (int)$this->getConfig("show_link", 1);

$show_image = (int)$this->getConfig("show_image", 1);
$imgWidth = (int)$this->getConfig("image_width", 300);
$imgHeight = (int)$this->getConfig("image_height", 300);
$show_name = $this->getConfig('show_name');
$show_short_description = $this->getConfig('show_short_description');
$show_price = $this->getConfig('show_price');
$show_rating = $this->getConfig('show_rating');
$show_addtocart = $this->getConfig('show_addtocart');
$show_addtolinks = $this->getConfig('show_addtolinks');
$alt_image = $this->getConfig('enable_swap');
$swap_image_number = $this->getConfig('swap_image_number', 1);
$enable_sale_icon = $this->getConfig('show_sale_icon');
$enable_new_icon = $this->getConfig('show_new_icon');
$enable_discount_icon = $this->getConfig('enable_discount_icon');
$short_max_char = (int)$this->getConfig("desc_maxchar", 100);
$show_learnmore = (int)$this->getConfig("show_learnmore", 1);

//Carousel setting
$lazyload = $this->getConfig("lazyload", 0);
$loop = $this->getConfig("loop", 0);
$auto_play_mode = $this->getConfig("auto_play", 0);
$show_nav = $this->getConfig("show_navigator", 1);
$custom_navigation = $this->getConfig("custom_navigation", 0);
$enable_pagination = $this->getConfig("show_pagination", 0);
$mobile_items = (int)$this->getConfig("mobile_items", 1);
$tablet_items = (int)$this->getConfig("tablet_items", 2);
$tablet_small_items = (int)$this->getConfig("tablet_small_items", 2);
$portrait_items = (int)$this->getConfig("portrait_items", 3);
$large_items = (int)$this->getConfig("large_items", 5);
$custom_items = $this->getConfig("custom_items", "");
$show_learnmore = $this->getConfig('show_learnmore');

$default_items = (int)$this->getConfig("default_items", 4);
$default_items = !empty($default_items)?(int)$default_items:4;

/*Deals Setting*/
$enable_deals = $this->getConfig("enable_deals", 0);
$enable_deals_block = Mage::getStoreConfig("productlist/general_setting/enable_countdown_js");
if(!$enable_deals_block && $enable_deals) {
    $enable_deals = 0;
}
$show_discount = $this->getConfig("show_discount", 1, "deals_setting");
$show_save_price = $this->getConfig("show_save_price", 1, "deals_setting");
$show_number_bought = $this->getConfig("show_number_bought", 1, "deals_setting");


$itemsperpage = $this->getConfig("items_per_page", $default_items);
$itemsperpage = $itemsperpage?(int)$itemsperpage: $default_items;
$cols = $default_items;

//End Product Information Settings

$current_rule = $this->getRuleModel();
if($show_rule_title)
{
    $title = $current_rule->getTitle();
}
if($show_countdowntimer){
    $widget_show_countdowntimer = $this->getData('show_countdowntimer');
    if($widget_show_countdowntimer == "false"){
        $show_countdowntimer = false;
    }
}
$items = $this->getDataItems();
$_helper = $this->helper('catalog/output');

//Load product item layout
$common_template = $default_path = "item.phtml";
if(!Mage::helper("productlist")->checkModuleInstalled("Ves_Themesettings")) {
    $common_template = $default_path = "vesproductlist_item.phtml";
}
if($custom_common = $this->getConfig("common_template", "")) {
    $common_template = $custom_common;
}
$current_catalog_product_path = Mage::getSingleton('core/design_package')->getBaseDir(array('_area' => 'frontend', '_type'=>'template'));
$current_catalog_product_path .= "/common/list/";

$base_catalog_product_path = Mage::getBaseDir('design')."/frontend/base/default/template/common/list/";

$load_file_path = false;

if(file_exists($current_catalog_product_path.$common_template)) { //Load in default template
    $load_file_path = $current_catalog_product_path.$common_template;
} elseif(file_exists($current_catalog_product_path.$default_path)) {
    $load_file_path = $current_catalog_product_path.$default_path;
} elseif(file_exists($base_catalog_product_path.$common_template)) { //Load in base template
    $load_file_path = $base_catalog_product_path.$common_template;
} elseif(file_exists($base_catalog_product_path.$default_path)) {
    $load_file_path = $base_catalog_product_path.$default_path;
}

//Bootstrap Carousel Settings
$max_cols = 12;
$cols = !empty($cols)?$cols:1;
$large = $max_cols/$cols;
$medium = floor((int)$max_cols/$portrait_items);
$small = floor((int)$max_cols/$tablet_items);
$mini = floor((int)$max_cols/$mobile_items);


?>
<?php if($items && $items->getSize()): ?>
    <div id="<?php echo $moduleId; ?>" class="widget-productlist-carousel bproductcarousel block <?php echo $this->getConfig("addition_cls"); ?> <?php if (isset($stylecls)&&$stylecls) echo 'block-'.$stylecls;?>" style="width:100%">
        <?php if( $title != '' && $title){ ?>
        <div class="block-title">
            <strong> <span><?php echo $title; ?> </span> </strong>
        </div>
        <?php } ?>

        <?php if($enable_rule_info && isset($rule_info) && $rule_info): ?>
            <?php
            $rule_shortDes = $processor->filter($rule_info->getShortDescription());
            ?>
            <?php if($enable_rule_short_description && $rule_shortDes != ''){ ?>
            <div class="rule-shortdescription">
                <?php echo $rule_shortDes; ?>
            </div>
            <?php } ?>

            <?php if($show_all_button){ ?>
            <div class="viewmore"><a href="<?php echo $rule_info->getUrl(); ?>" title="<?php echo $this->stripTags($rule_info->getTitle()); ?>" ><?php echo $this->__('Show All'); ?></a></div>
            <?php } ?>
        <?php endif; ?>

        <div class="widget-inner block-content">
            <div class="box-products carousel slide bootstrap-carousel-play <?php echo $class; ?>" id="productlistcarousel<?php echo $moduleId;?>">
                <?php if($show_nav == 1 && count($items) > $default_items ): ?>
                    <div class="carousel-controls">
                        <a class="carousel-control left" href="#productlistcarousel<?php echo $moduleId;?>"   data-slide="prev"><span class="fa fa-angle-left"></span></a>
                        <a class="carousel-control right" href="#productlistcarousel<?php echo $moduleId;?>"  data-slide="next"><span class="fa fa-angle-right"></span></a>
                    </div>
                <?php endif; ?>
                <div class="carousel-inner">
                    <?php $pages = array_chunk( $items->getItems(), $itemsperpage); ?>

                    <?php foreach ($pages as  $k => $_productCollection ) {  ?>
                    <div class="item <?php if($k==0) {?>first<?php } elseif($k == (count($pages) -1 )) {?>last<?php } ?> <?php if($k==0) {?>active<?php } ?> products-grid no-margin">

                        <?php foreach( $_productCollection as $i => $_product ) {  $i=$i+1;?>
                        <?php if( $cols == 1 || $i%$cols == 1 ) { ?>
                        <div class="row products-row product-item <?php echo $class; ?>" <?php echo $slider_height?' style="'.$slider_height.'"':'';?>>
                            <?php } ?>
                            <div class="col-lg-<?php echo $large;?> col-md-<?php echo $medium;?> col-sm-<?php echo $small; ?> col-xs-<?php echo $mini;?> _item product-col">

                                <!-- Product Item -->
                                <?php 
                                if($load_file_path) {
                                            require ($load_file_path); //Require file app/design/frontend/template package/template layout/template/common/list/item.phtml
                                        }
                                        ?>
                                        <!-- End Product Item -->

                                    </div>
                                    <?php if( $cols==1 || $i%$cols == 0 || $i==count($_productCollection) ) { ?>
                                </div>
                                <?php } ?>

                                <?php } //endforeach; ?>

                            </div>
                            <?php } //endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                jQuery('#productlistcarousel<?php echo $moduleId;?>').carousel({interval:<?php echo ( $auto_play_mode?(int)$this->getConfig("speed", 6000):'false') ;?>,auto:<?php echo $auto_play_mode?'true':'false';?>,pause:'hover', cycle: true});
            </script>
        <?php endif; ?>