<?php /** @var Cminds_Supplierfrontendproductuploader_Block_Product_Create $this */ ?>
<?php $categories = $this->getCategories(); ?>
<?php $attributes = $this->getAttributes(); ?>
<?php $product = $this->getProductObject(); ?>
<?php $this->setProduct($product); ?>
<?php $selectedCategories = $product->getCategoryIds(); ?>
<?php $mediaGallery = (isset($data['image'])) ? $data['image'] : array(); ?>

<?php $mediaGallery = $product->getMediaGalleryImages(); ?>

<?php $this->setSelectedCategories($selectedCategories); ?>
<?php $data = $this->getProductAttributes($product); ?>
<?php $isEditMode = $product->getId(); ?>
<?php $titleAction = 'Edit'; ?>
<?php
    $productAttributes = [];

    if ($product->getTypeId() === 'configurable') {
        $productAttributes = $product->getTypeInstance()->getConfigurableAttributes($product);
    }
?>
<?php if (Mage::registry('cloning')) : ?>
    <?php $titleAction = 'Clone'; ?>
<?php endif; ?>
<div class="container main-container vendor-container">
    <h1 class="text-center"><?php echo $this->__('%s Product', $titleAction); ?> - <?php echo $product->getName(); ?>
        <small>(SKU : <?php echo $product->getSku(); ?>)</small>
    </h1>
    <?php if ($product->getAdminProductNote() != null && $product->getAdminProductNote() != '') : ?>
        <div class="alerts">
            <div class="alert-message info">
                <a class="close" href="#">×</a>

                <p><strong>Admin Remark :</strong> <?php echo $product->getAdminProductNote(); ?></p>
            </div>
        </div>
    <?php endif; ?>
    <div class="row">
        <div class="col-md-12 form-container">
            <form name="product_create_form" id="product_create_form"
                  action="<?php echo Mage::getUrl('supplier/product/save') ?>" method="post"
                  enctype="multipart/form-data">
                <input type="hidden" name="type" value="<?php echo $this->getProductTypeId(); ?>"/>
                <?php if (Mage::registry('cloning')) : ?>
                    <input type="hidden" name="is_cloned" value="1"/>
                    <input type="hidden" name="attribute_set_id" value="<?php echo $this->getAttributeSetId() ?>"/>
                    <?php unset($data['sku']); ?>
                <?php else : ?>
                    <input type="hidden" name="product_id" value="<?php echo $product->getId(); ?>"/>
                <?php endif; ?>
                <div class="col-md-6 col-sm-6">
                    <div class="container form-group">
                        <div class="label-container">
                            <label for="name">
                                <?php echo $this->getLabel('name', 'Name', false); ?>
                                <span class="required"></span>:
                            </label>
                        </div>
                        <div class="input-container">
                            <input type="text" id="name" name="name" class="input-text form-control required-entry"
                                   value="<?php echo $product->getData('name'); ?>"/>
                        </div>
                    </div>
                    <div class="container form-group">
                        <div class="label-container">
                            <label for="short_description">
                                <?php echo $this->getLabel('short_description', 'Short Description', false); ?>
                                <span class="required"></span>:
                            </label>
                        </div>
                        <div class="input-container">
                            <textarea id="short_description" name="short_description"
                                      class="input-text form-control required-entry form-control wysiwyg"
                                      rows="15"><?php echo $product->getData('short_description'); ?></textarea>
                        </div>
                    </div>
                    <div class="container form-group">
                        <div class="label-container">
                            <label for="description">
                                <?php echo $this->getLabel('description', 'Detailed Description', false); ?>
                                <span class="required"></span>:
                            </label>
                        </div>
                        <div class="input-container">
                            <textarea id="description" name="description"
                                      class="input-text form-control form-control required-entry wysiwyg"
                                      rows="15"><?php echo $product->getData('description'); ?></textarea>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <legend><?php echo $this->__("Pricing"); ?></legend>
                    </div>
                    <div class="container form-group">
                        <div class="label-container">
                            <label for="price">
                                <?php echo $this->getLabel('price', 'Price', false); ?>
                                <span class="required"></span>:
                            </label>
                        </div>
                        <div class="input-container">
                            <input type="text"
                                   id="price"
                                   name="price"
                                   value="<?php echo number_format($product->getData('price'), 2, '.', ''); ?>"
                                   class="input-text form-control required-entry validate-number validate-greater-than-zero"
                            />
                        </div>
                    </div>
                    <div class="container form-group">
                        <div class="label-container">
                            <label for="special_price">
                                <?php echo $this->getLabel('special_price', 'Special Price', false); ?>:
                            </label>
                        </div>
                        <div class="input-container">
                            <input type="text" id="special_price" name="special_price"
                                   value="<?php echo number_format($product->getSpecialPrice(), 2, '.', ''); ?>"
                                   class="input-text form-control validate-number"/>
                        </div>
                    </div>
                    <div class="container form-group">
                        <div class="label-container">
                            <label for="special_price_from_date">
                                <?php echo $this->getLabel('special_price_from_date', 'Special Price From', false); ?>:
                            </label>
                        </div>
                        <div class="input-container">
                            <input type="text" id="special_price_from_date" name="special_price_from_date"
                                   value="<?php echo $product->getSpecialFromDate() ? date('m/d/Y', strtotime($product->getSpecialFromDate())) : ""; ?>"
                                   class="input-text form-control datepicker"/>
                        </div>
                    </div>
                    <div class="container form-group">
                        <div class="label-container">
                            <label for="special_price_to_date">
                                <?php echo $this->getLabel('special_price_to_date', 'Special Price To', false); ?>:
                            </label>
                        </div>
                        <div class="input-container">
                            <input type="text" id="special_price_to_date" name="special_price_to_date"
                                   value="<?php echo $product->getSpecialToDate() ? date('m/d/Y', strtotime($product->getSpecialToDate())) : ""; ?>"
                                   class="input-text form-control datepicker"/>
                        </div>
                    </div>
                    <?php if ($this->canAddSku()) : ?>
                        <div class="col-md-12">
                            <legend><?php echo $this->__("SKU Configuration"); ?></legend>
                        </div>
                        <div class="container form-group">
                            <div class="label-container">
                                <label for="sku">
                                    <?php echo $this->getLabel('sku', 'SKU', false); ?>
                                    <span class="required"></span>:
                                </label>
                            </div>
                            <div class="col-md-5 input-container">
                                <input type="text" id="sku" name="sku"
                                       value="<?php echo(isset($data['sku']) ? $data['sku'] : ''); ?>"
                                       class="input-text form-control  required-entry"/>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php if ($this->canShowWeightField()) : ?>
                        <div class="container form-group">
                            <div class="label-container">
                                <label for="weight">
                                    <?php echo $this->getLabel('weight', 'Product Weight', false); ?>
                                    <span class="required"></span>:
                                </label>
                            </div>
                            <div class="input-container">
                                <input type="text" id="weight" name="weight"
                                       value="<?php echo number_format($product->getData('weight'), 2, '.', ''); ?>"
                                       class="input-text form-control validate-number required-entry"/>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php if ($this->canManageStock()) : ?>
                        <div class="col-md-12">
                            <legend><?php echo $this->__("Inventory"); ?></legend>
                        </div>
                        <div class="form-group container">
                            <div class="label-container">
                                <label for="manage_stock">
                                    <?php echo $this->getLabel('manage_stock', $this->__('Manage Stock'), false); ?>
                                    <span class="required"></span>:
                                </label>
                            </div>
                            <div class="input-container">
                                <select name="manage_stock"
                                        id="manage_stock"
                                        class="input-text form-control ">
                                    <option value="1"<?php echo($this->getStockItem()->getManageStock() == 1) ? " selected" : ""?>>
                                        <?php echo $this->__("Yes"); ?>
                                    </option>
                                    <option value="0"<?php echo($this->getStockItem()->getManageStock() == 0) ? " selected" : ""?>>
                                        <?php echo $this->__("No"); ?>
                                    </option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group container inventory_management">
                            <div class="col-md-12 label-container row">
                                <label for="in_stock">
                                    <?php echo $this->getLabel('in_stock', $this->__('In Stock'), false); ?>
                                    <span class="required"></span>:
                                </label>
                            </div>
                            <div class="input-container">
                                <select name="in_stock"
                                        id="in_stock"
                                        class="input-text form-control ">
                                    <option value="1"<?php echo($this->getStockItem()->getIsInStock() == 1) ? " selected" : ""?>>
                                        <?php echo $this->__("Yes"); ?>
                                    </option>
                                    <option value="0"<?php echo($this->getStockItem()->getIsInStock() == 0) ? " selected" : ""?>>
                                        <?php echo $this->__("No"); ?>
                                    </option>
                                </select>
                            </div>
                        </div>
                        <?php if (!$this->isConfigurable()) : ?>
                            <div class="container form-group inventory_management"<?php echo($this->getStockItem()->getManageStock() == 0) ? " style='display:none;'" : ""?>>
                                <div class="label-container">
                                    <label for="qty">
                                        <?php echo $this->getLabel('qty', $this->__('QTY Available'), false); ?>
                                        <span class="required"></span>:
                                    </label>
                                </div>
                                <div class="input-container">
                                    <input type="text" id="qty" name="qty"
                                           value="<?php echo number_format($this->getStockItem()->getQty(), 2, '.', '') ?>"
                                           class="input-text form-control validate-number required-entry"
                                        <?php echo($this->getStockItem()->getManageStock() == 0) ? " disabled" : ""?>/>
                                </div>
                            </div>
                            <div class="container form-group inventory_management"<?php echo($this->getStockItem()->getManageStock() == 0) ? " style='display:none;'" : ""?>>
                                <div class="col-md-12 label-container row">
                                    <label for="inventory_min_qty">
                                        <?php echo $this->getLabel('inventory_min_qty', 'Qty for Item\'s Status to Become Out of Stock', false); ?>:
                                    </label>
                                </div>
                                <div class="col-md-5 input-container row">
                                    <input type="text" id="inventory_min_qty" name="inventory_min_qty"
                                           value="<?php echo $this->getStockItem()->getMinQty(); ?>"
                                           class="input-text form-control required-entry" />
                                </div>
                            </div>
                            <div class="container form-group inventory_management"<?php echo($this->getStockItem()->getManageStock() == 0) ? " style='display:none;'" : ""?>>
                                <div class="col-md-12 label-container row">
                                    <label for="is_qty_decimal">
                                        <?php echo $this->getLabel('is_qty_decimal', 'Qty Uses Decimals', false); ?>:
                                    </label>
                                </div>
                                <div class="input-container">

                                    <select name="is_qty_decimal"
                                            id="is_qty_decimal"
                                            class="input-text form-control ">
                                        <option value="1"<?php echo($this->getStockItem()->getIsQtyDecimal() == 1) ? " selected" : ""?>>
                                            <?php echo $this->__("Yes"); ?>
                                        </option>
                                        <option value="0"<?php echo($this->getStockItem()->getIsQtyDecimal() == 0) ? " selected" : ""?>>
                                            <?php echo $this->__("No"); ?>
                                        </option>
                                    </select>
                                </div>
                            </div>
                            <div class="container form-group inventory_management"<?php echo($this->getStockItem()->getManageStock() == 0) ? " style='display:none;'" : ""?>>
                                <div class="col-md-12 label-container row">
                                    <label for="is_decimal_divided">
                                        <?php echo $this->getLabel('is_decimal_divided', 'Can be Divided into Multiple Boxes for Shipping', false); ?>:
                                    </label>
                                </div>
                                <div class="col-md-5 input-container row"<?php echo($this->getStockItem()->getManageStock() == 0) ? " style='display:none;'" : ""?>>
                                    <select name="is_decimal_divided"
                                            id="is_decimal_divided"
                                            class="input-text form-control">
                                        <option value="1"<?php echo($this->getStockItem()->getIsDecimalDivided() == 1) ? " selected" : ""?>>
                                            <?php echo $this->__("Yes"); ?>
                                        </option>
                                        <option value="0"<?php echo($this->getStockItem()->getIsDecimalDivided() == 0) ? " selected" : ""?>>
                                            <?php echo $this->__("No"); ?>
                                        </option>
                                    </select>
                                </div>
                            </div>
                            <div class="container form-group inventory_management"<?php echo($this->getStockItem()->getManageStock() == 0) ? " style='display:none;'" : ""?>>
                                <div class="col-md-12 label-container row">
                                    <label for="backorders">
                                        <?php echo $this->getLabel('backorders', 'Backorders', false); ?>:
                                    </label>
                                </div>
                                <div class="input-container">
                                    <select id="backorders" name="backorders" class="select">
                                        <option value="0"<?php echo($this->getStockItem()->getBackorders() == 0) ? " selected" : ""?>>
                                            <?php echo $this->__("No Backorders"); ?>
                                        </option>
                                        <option value="1"<?php echo($this->getStockItem()->getBackorders() == 1) ? " selected" : ""?>>
                                            <?php echo $this->__("Allow Qty Below 0"); ?>
                                        </option>
                                        <option value="2"<?php echo($this->getStockItem()->getBackorders() == 2) ? " selected" : ""?>>
                                            <?php echo $this->__("Allow Qty Below 0 and Notify Customer"); ?>
                                        </option>
                                    </select>
                                </div>
                            </div>
                            <div class="container form-group inventory_management"<?php echo($this->getStockItem()->getManageStock() == 0) ? " style='display:none;'" : ""?>>
                                <div class="col-md-12 label-container row">
                                    <label for="notify_stock_qty">
                                        <?php echo $this->getLabel('notify_stock_qty', 'Notify for Quantity Below', false); ?>:
                                    </label>
                                </div>
                                <div class="input-container">
                                    <input type="text" id="notify_stock_qty" name="notify_stock_qty"
                                           value="<?php echo $this->getStockItem()->getNotifyStockQty()?>"
                                           class="input-text form-control required-entry" />
                                </div>
                            </div>
                        <?php endif; ?>
                        <div class="container form-group">
                            <div class="col-md-12 label-container row">
                                <label for="enable_qty_increments">
                                    <?php echo $this->getLabel('enable_qty_increments', 'Enable Qty Increments', false); ?>:
                                </label>
                            </div>
                            <div class="input-container">
                                <select name="enable_qty_increments"
                                        id="enable_qty_increments"
                                        class="input-text form-control ">
                                    <option value="1"<?php echo($this->getStockItem()->getEnableQtyIncrements() == 1) ? " selected" : ""?>><?php echo $this->__("Yes"); ?></option>
                                    <option value="0"<?php echo($this->getStockItem()->getEnableQtyIncrements() == 0) ? " selected" : ""?>><?php echo $this->__("No"); ?></option>
                                </select>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php if ($this->canSetMinQty() && !$this->isConfigurable()) : ?>
                        <?php $maxSaleQty = $this->getStockItem()->getMaxSaleQty(); ?>
                        <?php $minSaleQty = $this->getStockItem()->getMinSaleQty(); ?>
                        <div class="form-group container">
                            <div class="col-md-12 label-container">
                                <label for="inventory_max_sale_qty">
                                    <?php echo $this->getLabel('inventory_max_sale_qty', 'Maximum Qty Allowed in Shopping Cart', false); ?>:
                                </label>
                            </div>
                            <div class="input-container">
                                <input type="text" id="inventory_max_sale_qty" name="inventory_max_sale_qty"
                                       value="<?php echo ($maxSaleQty === null) ? 1 : $maxSaleQty; ?>"
                                       class="input-text form-control required-entry" />
                            </div>
                        </div>
                        <div class="form-group container">
                            <div class="col-md-12 label-container">
                                <label for="inventory_min_sale_qty">
                                    <?php echo $this->getLabel('inventory_min_sale_qty', 'Minimum Qty Allowed in Shopping Cart', false); ?>:
                                </label>
                            </div>
                            <div class="input-container">
                                <input type="text" id="inventory_min_sale_qty" name="inventory_min_sale_qty"
                                       value="<?php echo ($minSaleQty === null) ? 1 : $minSaleQty; ?>"
                                       class="input-text form-control required-entry" />
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php foreach ($attributes AS $attribute): ?>
                        <?php $attributeObj = Mage::getSingleton('eav/config')->getAttribute(Mage_Catalog_Model_Product::ENTITY, $attribute['code']); ?>
                        <?php if ($attributeObj->getData('available_for_supplier') == 0) {
                            continue;
                        } ?>
                        <?php if ((count($attributeObj->getApplyTo()) == 0 || in_array('simple', $attributeObj->getApplyTo()))) : ?>
                            <?php $attributeFrontend = $attributeObj->getFrontend(); ?>
                            <?php if ($product->getTypeId() === Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE && $attributeObj->getData('is_configurable') && $attributeObj->getData('frontend_input') == 'select') continue; ?>
                            <?php $isRequired = $attributeFrontend->getAttribute()->getIsRequired(); ?>
                            <div class="container form-group">
                                <div class="label-container">
                                    <label for="product_name">
                                        <?php echo $this->getLabel($attributeObj); ?>
                                        <?php if ($isRequired == 1) : ?>
                                            <span class="required"></span>
                                        <?php endif; ?>
                                    </label>
                                </div>
                                <div class="input-container">
                                    <?php echo $this->getAttributeHtml($attributeObj, $data); ?>
                                </div>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <?php if ($product->getAdminProductNote() != null && $product->getAdminProductNote() != '') : ?>
                        <div class="container form-group">
                            <div class="label-container">
                                <label
                                        for="notify_admin_about_change">
                                    <?php echo $this->__('Notify Admin About Change'); ?>
                                </label>
                            </div>
                            <div class="input-container">
                                <input type="checkbox" name="notify_admin_about_change" id="notify_admin_about_change"
                                       value="1"/>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="col-md-4 col-sm-5 col-sm-offset-1 col-md-offset-1 right sidebar">
                    <div class="form-group">
                        <div class="col-md-12 photo-content">
                            <h5><?php echo $this->__('Product Images'); ?></h5>

                            <div class="col-md-12">
                                <div class="row">
                                    <span class="file_upload_span btn btn-primary">
                                        <?php echo $this->__('Select and Upload Image') ?>
                                    </span>
                                    <input type="file" name="file_upload" id="file_upload" multiple/>
                                </div>
                            </div>
                            <?php $mainPhotoImage = ''; ?>
                            <?php foreach ($mediaGallery as $img) : ?>
                                <?php if ($product->getImage() == $img->getFile()) : ?>
                                    <?php $mainPhotoImage = $product->getImage() ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <input type="hidden" class="image hidden" name="main_photo" id="main_photo"
                                   value="<?php echo $mainPhotoImage ?>"/>

                            <div class="col-md-8 photos">
                                <ul class="photo panel-body">
                                    <?php foreach($mediaGallery AS $img) : ?>
                                        <?php if (file_exists(Mage::getBaseDir('media') . '/catalog/product' . $img->getFile())) : ?>
                                            <li class="thumbnail<?php echo ($mainPhotoImage == $img->getFile()) ? ' main' : '' ?>">
                                                <img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail', $img->getFile())->resize(171); ?>"
                                                     alt="<?php echo $this->htmlEscape($img->getLabel());?>"
                                                     title="<?php echo $this->htmlEscape($img->getLabel());?>"
                                                     data-name="<?php echo $img->getFile(); ?>"
                                                />
                                                <span class="remove"><i class="glyphicon glyphicon-remove"></i></span>
                                                <span class="default"><i class="glyphicon glyphicon-home"></i></span>
                                                <input type="hidden" class="image hidden" name="image[]" value="<?php echo $img->getFile(); ?>" /></li>
                                            </li>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <?php if (!$this->isAssigned()) : ?>
                        <ul class="category-list">
                            <h5><?php echo $this->__('Product Categories'); ?></h5>
                            <?php echo $this->getCategoriesListHtml(); ?>
                        </ul>
                    <?php endif; ?>
                    <?php if (Mage::registry('cloning')) : ?>
                        <ul class="super-attributes">
                            <h5><?php echo $this->__('Configurable Attributes'); ?></h5>
                            <?php foreach ($productAttributes as $attribute) : ?>
                                <?php $attributeObj = Mage::getSingleton('eav/config')
                                    ->getAttribute(Mage_Catalog_Model_Product::ENTITY, $attribute
                                        ->getProductAttribute()
                                        ->getAttributeCode()); ?>
                                <?php if (!$attributeObj->getData('is_user_defined')) continue; ?>
                                <?php if (!$attributeObj->getData('is_configurable')) continue; ?>
                                <?php if ($attributeObj->getData('frontend_input') != 'select') continue; ?>
                                <li><input type="checkbox" name="attributes[]"
                                           id="<?php echo $attributeObj->getAttributeCode(); ?>"
                                           value="<?php echo $attributeObj->getAttributeCode(); ?>"
                                           required
                                    />
                                    <label
                                            for="<?php echo $attributeObj->getAttributeCode(); ?>"><?php echo $attributeObj->getFrontendLabel(); ?></label>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                    <?php if ($this->isDownloadable()) : ?>
                        <?php $links = $this->getLinks(); ?>
                        <?php if (count($links) > 0): ?>
                            <ul class="list-unstyled">
                                <h5><?php echo $this->__("File"); ?></h5>
                                <?php foreach ($links as $link) : ?>
                                    <?php $url = ''; ?>
                                    <?php if ($link->getLinkType() == 'url') $url = $link->getLinkUrl(); ?>
                                    <?php if ($link->getLinkType() != 'url') : ?>
                                        <li>
                                            <input type="file" name="downloadable_upload" id="downloadable_upload"/>
                                        </li>
                                    <?php else : ?>
                                        <li>
                                            <input type="text"
                                                   id="sku"
                                                   name="file_url"
                                                   class="input-text form-control"
                                                   value="<?php echo $url; ?>"
                                            />
                                        </li>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                        <?php else: ?>
                            <ul class="category-list">
                                <h5><?php echo $this->__('Download data');?></h5>
                                <li>
                                    <span><?php echo $this->__('Download title'); ?></span>
                                    <input type="text" name="downloadable_title" id="downloadable_title"
                                           class="input-text form-control required"/>
                                </li>
                                <h5><?php echo $this->__("File"); ?></h5>
                                <li>
                                    <input type="file" name="downloadable_upload" id="downloadable_upload" />
                                </li>
                                <li><?php echo $this->__("Or"); ?></li>
                                <li>
                                    <input type="text" id="sku" name="file_url"
                                           class="input-text form-control "/>
                                </li>
                            </ul>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
                <span class="clearfix"></span>

                <div class="col-md-2 col-sm-4 col-sm-offset-4 col-md-offset-5 btn-save-fix">
                    <!-- <input type="hidden" class="validate-ckeditor"/> -->
                    <input type="hidden" class="validate-categories"/>
                    <input type="submit" name="submit" class="btn btn-primary save-button"
                           value="<?php echo $this->__('Save Product') ?>"/>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="slideshow-container">
    <div class="slideshow"></div>
</div>
<script type="text/javascript">
    //< ![CDATA[
    var customForm = new VarienForm('product_create_form');
    <?php if (!$this->isAssigned()) : ?>
    Validation.add('validate-categories','Please Select Category',function(){
        if(jQuery('li.checkbox-group.required :checkbox:checked').length > 0) {
            return true;
        }
        return false;
    });
    <?php endif; ?>
    //]]>


    jQuery(document).ready(function ($) {
        jQuery('.datepicker').datepicker();
        var limit = <?php echo $this->getMaxImagesCount() ?>;
        var photos = 0;
        jQuery('input[id=file_upload]'). change(function(e) {
            photos = this.files.length;
        });

        jQuery('#file_upload').fileupload({
            url: '<?php echo Mage::getUrl('supplier/product/upload') ?>',
            dataType: 'json',
            done: function (e, data) {
                if (data.result.success) {
                    $('.photo.panel-body').append('<li class="thumbnail"><img src="' + data.result.url + '" alt="" data-name="' + data.result.name + '"/><span class="remove"><i class="glyphicon glyphicon-remove" title="Remove This Picture"></i></span><span class="default"><i class="glyphicon glyphicon-home" title="<?php echo $this->__("Set As Main Picture"); ?>"></i></span><input type="hidden" class="image hidden" name="image[]" value="' + data.result.name + '" /></li>');
                } else {
                    alert(data.result.message);
                }
            }
        })
            .prop('disabled', !jQuery.support.fileInput)
            .parent().addClass(jQuery.support.fileInput ? undefined : 'disabled')
            .on('fileuploadadd', function (e, data) {
                if ($j('.thumbnail:visible').length + photos > limit) {
                    alert('The upload limit has been reached');
                    return false;
                }
            });

        jQuery(document).on('click', 'li span.remove', function ($) {
            var img = jQuery(this).prev();
            var imgName = jQuery(img).attr('data-name');

            jQuery('input.image.hidden').each(function (el) {
                if (jQuery(this).val() == imgName) {
                    jQuery(this).val('');
                }
            });
            jQuery(this).parent().fadeOut();

        });

        jQuery(document).on('click', 'li span.default', function ($) {
            var img = jQuery(this).prev().prev();
            var imgName = jQuery(img).attr('data-name');
            var mainPhotoInput = jQuery('#main_photo');
            mainPhotoInput.val(imgName);
            jQuery('li.thumbnail.main').removeClass('main');
            img.parent().addClass('main');
        });

        // CKEDITOR.replace( 'description' );
        // CKEDITOR.replace( 'short_description' );

        jQuery(document).on('click', 'div.alerts .close', function (e) {
            e.preventDefault();
            jQuery(this).parent().slideUp();
        });

        // jQuery(".save-button").click(function(e){
        //     CKEDITOR.instances.description.updateElement();
        //     CKEDITOR.instances.short_description.updateElement();
        // });

        jQuery("#manage_stock").change(function(){
            var inventoryFields = jQuery(".inventory_management");
            if(jQuery(this).val() == 1) {
                inventoryFields.show();
                inventoryFields
                    .find("input")
                    .removeAttr("disabled");
            } else {
                inventoryFields.hide();
                inventoryFields
                    .find("input")
                    .attr("disabled", "disabled")
            }
        });

        Validation.add('validate-ckeditor','Please fill description fields',function(){
            if(!CKEDITOR.instances.description._.data
                || !CKEDITOR.instances.short_description._.data
            ) {
                return false;
            }

            return true;
        });
    });
</script>