<div class="product-block">
    <div class="image">
        <?php if($enable_sale_icon || $enable_new_icon){ ?>
        <div class="icon">
            <?php  //Sale Icon ?>
            <?php
            if($enable_sale_icon) {
                    // Get the Special Price
                $specialprice = $_product->getSpecialPrice();
                    // Get the Special Price FROM date
                $specialPriceFromDate = $_product->getSpecialFromDate();
                    // Get the Special Price TO date
                $specialPriceToDate = $_product->getSpecialToDate();
                    // Get Current date
                $today =  time();
                if ($specialprice) {
                    if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)) {
                        ?>
                        <span class="onsale"><span><?php echo $this->__("Sale");?></span></span>
                        <?php
                    }
                }
            }
            ?>
            <?php // New icon ?>
            <?php
            if($enable_new_icon) {
                $is_new = $ves->checkProductIsNew( $_product );
                if($is_new) { ?>
                <span class="new-icon"><span><?php echo $this->__("New");?></span></span>
                <?php
            }
        }
        ?>
    </div>
    <?php } ?>

    <div class="product-image">
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
            src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>"
            alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
        </a>
        <?php if($alt_image){ ?>
        <a class="hover-image" href="<?php echo $_product->getProductUrl(); ?>">
            <?php
            $alt_image_url = $ves->getAltImgHtml($_product, $imgWidth, $imgHeight);
            if($alt_image_url!=''){ ?>
            <img src="<?php echo $alt_image_url ?>" width="<?php echo $imgWidth; ?>" height="<?php echo $imgHeight; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            <?php }else{
                $alt_image_url = $ves->getAltImgHtml($_product, $imgWidth, $imgHeight);
                ?>
                <img src="<?php echo $alt_image_url ?>" width="<?php echo $imgWidth; ?>" height="<?php echo $imgHeight; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                <?php } ?>
            </a>
            <?php } ?>
        </div>

        <?php // Quickview Block ?>
        <?php if ($show_quickview) { ?>
        <div class="quickview">
            <?php if($show_quickview == 1 && $hover_effect){ //Display on hover ?>
            <div class="display-onhover quickview-wrapper">
                <?php } ?>
                <a href='<?php echo $ajax->getQuickviewUrl($_product); ?>' class='fancybox-play tooltip_container button' data-ftype='iframe' data-hideOnContentClick="true" data-overlayOpacity="true" data-width="<?php echo $popup_quickview_width ?>" data-height="<?php echo $popup_quickview_height; ?>" data-scrolling="yes" data-show-close-button="true" data-verlay-opacity="0.8" data-show-overlay="true" id='quickview-fancybox<?php echo $_product->getId()?>'><i class="fa fa-search-plus"></i> <span><?php echo $this->__('Quick view') ?> </span></a>
                <?php if($show_quickview == 1 && $hover_effect){ ?>
            </div>
            <?php } ?>
        </div>
        <?php } ?>
    </div>

    <div class="product-info">
        <div class="actions">
            <?php // AddToCart Block ?>
            <?php if ($show_addtocart == 1 || $show_addtocart == 2){ ?>
            <?php if($show_addtocart == 1 && $hover_effect){ //Display on hover ?>
            <div class="display-onhover addtocart-wrapper">
                <?php } ?>
                <?php if($_product->isSaleable()): ?>
                    <?php if($ajaxcart) { ?>
                    <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart ajx-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php } else { ?>
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <a href='<?php echo $ajax->getQuickviewUrl($_product); ?>' class='fancybox-play tooltip_container hidden' data-ftype='iframe' data-hideOnContentClick="true" data-overlayOpacity="true" data-width="<?php echo $popup_quickview_width ?>" data-height="<?php echo $popup_quickview_height; ?>" data-scrolling="yes" data-show-close-button="true" data-verlay-opacity="0.8" data-show-overlay="true" id='fancybox<?php echo $_product->getId()?>' ></a>
                    <?php }  ?>
                    <?php } else { ?>
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php } ?>
                <?php else: ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
                <?php if($show_addtocart == 1 && $hover_effect){ ?>
            </div>
            <?php } ?>
            <?php } ?>

            <?php // AddtoLinks Block ?>
            <?php if ($show_addtolinks == 1 || $show_addtolinks == 2){ ?>
            <?php if($show_addtolinks == 1 && $hover_effect){ //Display on hover ?>
            <div class="display-onhover addtolink-wrapper">
                <?php } ?>
                <ul class="add-to-links">
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"> <i class="fa fa-heart-o"></i> <span> <?php echo $this->__('Add to Wishlist') ?> </span> </a></li>
                    <?php endif; ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"> <i class="fa fa-files-o"></i> <span><?php echo $this->__('Add to Compare') ?> </span> </a></li>
                    <?php endif; ?>
                </ul>
                <?php if($show_addtolinks == 1 && $hover_effect){ ?>
            </div>
            <?php } ?>
            <?php } ?>

        </div>
        <?php // Name Block ?>
        <?php if ($show_name == 1 || $show_name == 2){ ?>
        <?php if($show_name == 1 && $hover_effect){ //Display on hover ?>
        <div class="display-onhover name-wrapper">
            <?php } ?>
            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
            <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
            <?php if($show_name == 1 && $hover_effect){ ?>
        </div>
        <?php } ?>
        <?php } ?>

         <?php
        // Provides extra blocks on which to hang some features for products in the list
        // Features providing UI elements targeting this block will display directly below the product name
        if ($this->getChild('name.after')) {
            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
            foreach ($_nameAfterChildren as $_nameAfterChildName) {
                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                $_nameAfterChild->setProduct($_product);
                echo $_nameAfterChild->toHtml();
            }
        }
        ?>

        <?php // Price Block ?>
        <?php if ($show_price == 1 || $show_price == 2){ ?>
        <?php if($show_price == 1 && $hover_effect){ //Display on hover ?>
        <div class="display-onhover price-wrapper">
            <?php } ?>
            <?php echo $this->getPriceHtml($_product, true) ?>
            <?php if($show_price == 1 && $hover_effect){ ?>
        </div>
        <?php } ?>
        <?php } ?>

        <?php // Rating Block ?>
        <?php if ($show_rating == 1 || $show_rating == 2){ ?>
        <?php if($show_rating == 1 && $hover_effect){ //Display on hover ?>
        <div class="display-onhover rating-wrapper">
            <?php } ?>
            <?php echo $this->getReviewsSummaryHtml($_product, true, true) ?>
            <?php if($show_rating == 1 && $hover_effect){ ?>
        </div>
        <?php } ?>
        <?php } ?>

        <!-- Countdown Timer -->
        <?php if( isset($_product) && $_product->getFinalPrice() < $_product->getPrice() && $show_countdowntimer){
            $date1 = date('G:i:s', strtotime($_product->getSpecialToDate()));
            if ($date1 == "0:00:00") {
                $targetDate = date('m/d/Y \2\3\:\5\9\:\0\0', strtotime($_product->getSpecialToDate()));
            }else{
                $targetDate = date('m/d/Y G:i:s', strtotime($_product->getSpecialToDate()));
            }
            ?>
            <?php if($show_countdowntimer == 1 && $hover_effect){ //Display on hover ?>
            <div class="display-onhover countdown-timer-wrapper">
                <?php } ?>
                <div class="countdown-timmer">
                    <div class="item-detail">
                        <div class="timer-explain">(<?php echo date('m/d/Y', strtotime($_product->getSpecialToDate())); ?>)</div>
                    </div>
                    <div id="item<?php echo $mId; ?>countdown_<?php echo $_product->getId(); ?>" class="item-countdown"></div>
                    <script type="text/javascript">
                        jQuery(document).ready(function($){
                            $("#item<?php echo $mId; ?>countdown_<?php echo $_product->getId(); ?>").lofCountDown({
                                formatStyle:2,
                                TargetDate:"<?php echo $targetDate; ?>",
                                DisplayFormat:"<ul><li>%%D%% <div><?php echo $this->__('Day');?></div></li><li> %%H%% <div><?php echo $this->__('Hours');?></div></li><li> %%M%% <div><?php echo $this->__('Mins');?></div></li><li> %%S%% <div><?php echo $this->__('Secs');?></div></li></ul>",
                                FinishMessage:"<?php echo $this->__('Expired');?>",
                            });
                        });
                    </script>
                </div>
                <?php if($show_countdowntimer == 1 && $hover_effect){ ?>
            </div>
            <?php } ?>
            <?php } ?>

            <?php // Short Description Block ?>
            <?php if ($show_short_description == 1 || $show_short_description == 2){ ?>
            <?php if($show_short_description == 1 && $hover_effect){ //Display on hover ?>
            <div class="display-onhover shortdes-wrapper">
                <?php } ?>
                <div class="desc std">
                    <?php
                    $short_description = $_product->getShortDescription();
                    if((int)$short_max_char>0){
                        $short_description = Mage::helper('themesettings')->subString($short_description,$short_max_char);
                    }
                    ?>
                    <?php echo $_helper->productAttribute($_product, $short_description, 'short_description') ?>
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <?php if($show_learnmore): ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    <?php endif; ?>
                </div>
                <?php if($show_short_description == 1 && $hover_effect){ ?>
            </div>
            <?php } ?>
            <?php } ?>

        </div>
    </div>