<?php if($crumbs && is_array($crumbs)): ?>
    <div class="breadcrumbs">
        <ul xmlns:v="http://rdf.data-vocabulary.org/#">
            <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
                <li class="<?php echo $_crumbName ?>" typeof="v:Breadcrumb">
                    <?php if($_crumbInfo['link']): ?>
                        <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>" rel="v:url" property="v:title">
                            <span><?php echo $this->htmlEscape($_crumbInfo['label']) ?></span>
                        </a>
                    <?php elseif($_crumbInfo['last']): ?>
                        <span rel="v:child" property="v:title">
                            <strong><?php echo $this->htmlEscape($_crumbInfo['label']) . ' for sale' ?></strong>
                        </span>
                    <?php else: ?>
                        <span><?php echo $this->htmlEscape($_crumbInfo['label']) ?></span>
                    <?php endif; ?>
                    <?php if(!$_crumbInfo['last']): ?>
                        <span>/ </span>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>