<?php /** @var Cminds_Supplierfrontendproductuploader_Helper_Data $helper */ ?>
<?php $helper = Mage::helper('supplierfrontendproductuploader'); ?>
<?php $customAttributes = $helper->getRegistrationAttributes(); ?>
<div class="container vendor-container">
    <div class="col-main">
        <ul class="messages">
            <?php $messages = Mage::getSingleton('customer/session')->getMessages(true); ?>
            <?php foreach ($messages->getItems('error') AS $msg): ?>
                <li class="error-msg">
                    <ul>
                        <li><span><?php echo $msg->getCode(); ?></span></li>
                    </ul>
                </li>
            <?php endforeach; ?>
        </ul>
        <div class="page-title">
            <h1><?php echo $this->__("Create New Account"); ?></h1>
        </div>
        <form action="<?php echo Mage::getUrl('supplier/register/createpost') ?>" method="post"
              class="form-horizontal scaffold-form" id="registerForm" accept-charset="utf-8">
            <div class="form-list">
                <div class="field">
                    <label for="firstname" class="control-label required">
                        <?php echo $this->__('First Name'); ?><em>*</em>
                    </label>
                    <div class="input-box">
                        <input name="group_id" type="hidden"
                               value="<?php echo Mage::getStoreConfig('supplierfrontendproductuploader_catalog/login/register_customer_group') ?>"
                               id="group_id" class="input-text required-entry">
                        <input name="firstname" type="text" value="" id="firstname" class="input-text required-entry">
                    </div>
                </div>

                <div class="field">
                    <label for="lastname" class="control-label required">
                        <?php echo $this->__('Last Name'); ?><em class="text-error">*</em>
                    </label>
                    <div class="input-box"><input name="lastname" type="text" value="" id="lastname"
                                                  class="input-text required-entry">
                    </div>
                </div>

                <div class="field">
                    <label for="email" class="control-label required">
                        <?php echo $this->__('Email Address'); ?><em class="text-error">*</em>
                    </label>
                    <div class="input-box"><input name="email" type="text" value="" id="email"
                                                  class="input-text validate-email"></div>
                </div>
                <?php foreach ($customAttributes as $attributeCode) : ?>
                    <?php if (!$attributeCode) continue; ?>
                    <?php $attribute = Mage::getModel('customer/customer')->getResource()->getAttribute($attributeCode); ?>
                    <?php if (!$attribute) : ?>
                        <?php continue; ?>
                    <?php endif; ?>
                    <?php $attribute = $attribute->getFrontend()->getAttribute(); ?>
                    <?php if ($attribute->getBackendType() !== 'text') :?>
                        <?php continue; ?>
                    <?php endif; ?>
                    <label for="<?php echo $this->escapeHtml($attributeCode); ?>" class="control-label required">
                        <?php echo $attribute->getFrontendLabel(); ?><em class="text-error">*</em>
                    </label>
                    <?php if ($attribute->getFrontendInput() === 'textarea') : ?>
                        <div class="input-box">
                            <textarea cols=10 name="<?php echo $this->escapeHtml($attributeCode); ?>" id="<?php echo $this->escapeHtml($attributeCode); ?>" class="input-text required-entry"></textarea>
                        </div>
                    <?php else: ?>
                        <div class="input-box">
                            <input name="<?php echo $this->escapeHtml($attributeCode); ?>" type="text" id="<?php echo $this->escapeHtml($attributeCode); ?>" class="input-text required-entry">
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
                <div class="field">
                    <label for="city" class="control-label required">
                        <?php echo $this->__('Password'); ?><em class="text-error">*</em>
                    </label>
                    <div class="input-box"><input name="password" type="password" value="password" id="password"
                                                  class="input-text required-entry validate-password"></div>
                </div>

                <div class="field">
                    <label for="country" class="control-label required">
                        <?php echo $this->__('Retype Password'); ?><em class="text-error">*</em>
                    </label>
                    <div class="input-box"><input name="confirmation" type="password" value="" id="confirmation"
                                                  class="input-text required-entry required-entry validate-cpassword">
                    </div>
                </div>
                <?php if ($helper->forceTermsToRegister()) : ?>
                    <div class="field">
                        <div class="input-box">
                            <input name="terms" type="checkbox" id="terms"
                                   class="input-checkbox required-entry">
                        </div>
                        <label for="terms" class="control-label required">
                            <?php echo $this->__('I agree to the <a href="%s" target="_blank">terms and conditions</a> of service', $helper->getTermsPageUrl()); ?>
                            <em class="text-error">*</em>
                        </label>
                    </div>
                <?php endif; ?>
                <div class="form-actions buttons-set">
                    <button type="submit"
                            class="button btn btn-large btn-primary"><span><span><?php echo $this->__('Create Account'); ?></span></span></button>
                    <p class="required"><?php echo $this->__('* Required Fields'); ?></p>
                </div>
            </div>
        </form>
    </div> <!-- .span8 -->
</div>

<script type="text/javascript">
    //< ![CDATA[
    var customForm = new VarienForm('registerForm');
    //]]>
</script>