<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:90%;"><h3 class="icon-head head-brand"><?php /* echo Mage::helper('ves_brand')->__('Brands Manager') */  echo Mage::helper('ves_brand')->__('Budges Manager') ?></h3></td>
        <td class="a-right">
            <?php echo $this->getAddNewButtonHtml() ?>
        </td>
		<td class="a-right">
            <?php echo $this->getMassResizeButtonHtml() ?>
        </td>
		<td class="a-right">
            <?php echo $this->getMassRewriteCatButtonHtml() ?>
        </td>
    </tr>
</table>
</div>
<?php  echo $this->getStoreSwitcherHtml() ?>
<div>
    <?php echo $this->getGridHtml() ?>
</div>