<?php
$_product = $this->getProduct();
$rule = Mage::registry('current_rule');
$id = rand(1,9)+rand();
$enable_deals_block = Mage::getStoreConfig("productlist/general_setting/enable_countdown_js");

?>
<!-- TIMER -->
<?php
if($_product->getSpecialToDate() != '' && $rule->getData('show_timer_countdown') && $enable_deals_block){
    $date1 = date('G:i:s', strtotime($_product->getSpecialToDate()));
    if ($date1 == "0:00:00") {
        $targetDate = date('m/d/Y \2\3\:\5\9\:\0\0', strtotime($_product->getSpecialToDate()));
    }else{
        $targetDate = date('m/d/Y G:i:s', strtotime($_product->getSpecialToDate()));
    }
    ?>
    <div class="productdeals">
        <div class="item-detail">
            <div class="timer-explain">(<?php echo date('m/d/Y', strtotime($_product->getSpecialToDate())); ?>)</div>
        </div>
        <div id="item<?php echo $id; ?>countdown_<?php echo $_product->getId(); ?>" class="item-countdown"></div>
        <script type="text/javascript">
            jQuery(document).ready(function($){
                $("#item<?php echo $id; ?>countdown_<?php echo $_product->getId(); ?>").lofCountDown({
                    formatStyle:2,
                    TargetDate:"<?php echo $targetDate; ?>",
                    DisplayFormat:"<ul><li>%%D%% <div><?php echo $this->__('Day');?></div></li><li> %%H%% <div><?php echo $this->__('Hours');?></div></li><li> %%M%% <div><?php echo $this->__('Mins');?></div></li><li> %%S%% <div><?php echo $this->__('Secs');?></div></li></ul>",
                    FinishMessage:"<?php echo $this->__('Expired');?>",
                });
            });
        </script>
    </div>
    <?php } ?>